### PR TITLE
Header_parser-Project

### PR DESCRIPTION
**Pull request by Sr-kamogelo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by Sr-kamogelo** [comment]
This is my Free code Camp Header parser Request project

**Comment by gikf** [comment]
Hey @Sr-kamogelo

Looks like this PR was supposed to be made on your own fork, instead of the original boilerplate repository.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by Sr-kamogelo** [comment]
Hi Can you please help me out I am totally  confused and I don't know how
to hand in the link to my github code or backend project

**Comment by gikf** [comment]
Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours.

Thank you and happy coding.

**Pull request closed without merging**
