### PR TITLE
fix(config/deps): update and a little cleanup

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

1. Update `.replit` config.

2. Update package.json and package.lock.json

3. Downgrade to Express.js V4. The package.json file had an alpha version of Express. I would suggest we avoid using that just to be safe.

4. Delete old files no longer needed.

### CODE REVIEW

**Comment by lasjorg** [comment]
I forgot about prettier, it does some weird formatting of the `.replit` file. I added a `.prettierignore`.

I should update the other PRs as well if I remember.

**Review by moT01 — COMMENTED** [review]
I loaded this one up and it didn't give me the correct language:
Screen Shot 2022-07-15 at 2 18 42 PM

Add the .gitattributes here @lasjorg? Curious, were you getting that or did it give you node? Wondering if we should add it to all the others in case it's flaky or something.

**Comment by lasjorg** [comment]
@moT01 No, I was probably just trying to do too many things at once, .gitattributes added.

**Review by moT01 — APPROVED** [review]
LGTM 🎉

**Review by RandellDawson — APPROVED** [review]

**Comment by RandellDawson** [comment]
Thank you for your contribution to the repo! 👍

**Pull request merged**
